package security;

import util.Constants;

import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.security.spec.InvalidKeySpecException;
import java.util.Arrays;

/**
 * PasswordUtil.java
 * -----------------
 * Handles all password-related security operations:
 *   1. Generating a random salt
 *   2. Hashing a password with PBKDF2WithHmacSHA256
 *   3. Verifying a submitted password against a stored hash
 *   4. Converting between byte arrays and hex strings
 *
 * ---------------------------------------------------------------
 * WHY NOT STORE PASSWORDS DIRECTLY?
 * ---------------------------------------------------------------
 * If an attacker gains access to our users.dat file, they must NOT
 * be able to read anyone's password.  If we stored "krishna123"
 * directly, they instantly know the password.
 *
 * Instead we store a HASH — a one-way mathematical transformation.
 * Given the hash you cannot reverse it back to the original password.
 *
 * ---------------------------------------------------------------
 * WHAT IS A SALT?
 * ---------------------------------------------------------------
 * A salt is a random byte array generated ONCE per user at
 * registration time.  It is mixed with the password before hashing.
 *
 * Without a salt, two users with the same password produce the same
 * hash, making "rainbow table" attacks possible (pre-computed hash lists).
 * With a unique salt, even identical passwords produce completely
 * different hashes.
 *
 * The salt is NOT secret — it is stored alongside the hash.
 * Its only job is to make each hash unique.
 *
 * ---------------------------------------------------------------
 * WHAT IS PBKDF2?
 * ---------------------------------------------------------------
 * Password-Based Key Derivation Function 2.
 * It applies a hash function (HmacSHA256 in our case) repeatedly
 * — 310,000 times by default — making brute-force attacks very slow.
 * An attacker trying millions of password guesses per second is
 * slowed to a crawl.
 *
 * ---------------------------------------------------------------
 * SECURITY NOTE FOR INTERVIEWS:
 * ---------------------------------------------------------------
 * This implementation is suitable for a student/placement project.
 * In production, consider using a library like Spring Security's
 * BCrypt or Argon2, which are purpose-built password hashing
 * functions with built-in salting.  PBKDF2 is perfectly acceptable
 * and is used in many real-world systems.
 */
public class PasswordUtil {

    // SecureRandom produces cryptographically strong random numbers.
    // It seeds itself from the OS entropy pool, unlike Math.random()
    // which uses a simple pseudo-random algorithm.
    // We create ONE instance and reuse it — construction is expensive.
    private static final SecureRandom SECURE_RANDOM = new SecureRandom();

    // The PBKDF2 algorithm name accepted by SecretKeyFactory
    private static final String PBKDF2_ALGORITHM = "PBKDF2WithHmacSHA256";


    // ----------------------------------------------------------------
    // PUBLIC API
    // ----------------------------------------------------------------

    /**
     * Generate a new random salt.
     * Call this ONCE per user at registration time.
     *
     * @return a byte array of length Constants.SALT_LENGTH (16 bytes)
     */
    public static byte[] generateSalt() {
        byte[] salt = new byte[Constants.SALT_LENGTH];
        SECURE_RANDOM.nextBytes(salt);   // Fill with cryptographically random bytes
        return salt;
    }

    /**
     * Hash a password using PBKDF2WithHmacSHA256.
     *
     * Steps:
     *   1. Convert the password String to a char array (required by PBEKeySpec)
     *   2. Create a PBEKeySpec with password + salt + iteration count + key length
     *   3. Use SecretKeyFactory to derive the key (this is the slow, secure step)
     *   4. Return the derived bytes as a hex string
     *
     * @param password  the plaintext password the user typed
     * @param salt      the random salt generated by generateSalt()
     * @return          the hex-encoded PBKDF2 hash
     * @throws RuntimeException if PBKDF2WithHmacSHA256 is not available (should never happen on standard JDK)
     */
    public static String hashPassword(String password, byte[] salt) {
        try {
            // PBEKeySpec holds the inputs to the key derivation function.
            // We convert password to char[] because:
            //   - Strings are immutable and stay in memory until GC runs
            //   - char[] can be explicitly zeroed after use (more secure)
            PBEKeySpec spec = new PBEKeySpec(
                    password.toCharArray(),          // the password
                    salt,                             // the salt
                    Constants.PBKDF2_ITERATIONS,     // number of hash iterations
                    Constants.PBKDF2_KEY_LENGTH      // output length in bits
            );

            // SecretKeyFactory performs the actual PBKDF2 computation
            SecretKeyFactory factory = SecretKeyFactory.getInstance(PBKDF2_ALGORITHM);

            // generateSecret() applies PBKDF2 — this is the computationally
            // expensive step that slows down brute-force attacks
            byte[] hash = factory.generateSecret(spec).getEncoded();

            // Zero out the PBEKeySpec's internal copy of the password
            // so it doesn't linger in memory longer than necessary
            spec.clearPassword();

            // Convert raw bytes to a readable hex string for storage
            return bytesToHex(hash);

        } catch (NoSuchAlgorithmException | InvalidKeySpecException e) {
            // These exceptions should never occur on a standard JDK 8+
            throw new RuntimeException("Password hashing failed: " + e.getMessage(), e);
        }
    }

    /**
     * Verify a submitted password against a stored hash.
     *
     * We hash the submitted password with the SAME salt used at
     * registration, then compare the two hashes.
     *
     * IMPORTANT: We use MessageDigest.isEqual() style constant-time
     * comparison via Arrays.equals after hashing — in practice, for
     * PBKDF2 the comparison timing is dominated by the hash computation
     * itself, but using a constant-time compare is still best practice.
     *
     * @param submittedPassword  the plaintext password the user just typed
     * @param salt               the stored salt for this user
     * @param storedHash         the stored hex hash for this user
     * @return                   true if the password matches, false otherwise
     */
    public static boolean verifyPassword(String submittedPassword,
                                         byte[] salt,
                                         String storedHash) {
        // Hash the submitted password with the same salt
        String submittedHash = hashPassword(submittedPassword, salt);

        // Compare using constant-time comparison to resist timing attacks.
        // A simple equals() comparison may return early on the first
        // differing character, leaking timing information.
        return constantTimeEquals(submittedHash, storedHash);
    }


    // ----------------------------------------------------------------
    // CONVERSION HELPERS  (package-private so tests can use them)
    // ----------------------------------------------------------------

    /**
     * Convert a byte array to a lowercase hex String.
     * Example: {0x0A, 0xFF} → "0aff"
     *
     * @param bytes  the byte array to convert
     * @return       hex string representation
     */
    public static String bytesToHex(byte[] bytes) {
        StringBuilder sb = new StringBuilder(bytes.length * 2);
        for (byte b : bytes) {
            // & 0xFF converts signed byte to unsigned int (0-255)
            // %02x formats as 2-digit lowercase hex, padding with 0 if needed
            sb.append(String.format("%02x", b & 0xFF));
        }
        return sb.toString();
    }

    /**
     * Convert a hex String back to a byte array.
     * Example: "0aff" → {0x0A, 0xFF}
     *
     * @param hex  the hex string (must have even length)
     * @return     byte array
     * @throws IllegalArgumentException if the string is not valid hex
     */
    public static byte[] hexToBytes(String hex) {
        if (hex == null || hex.length() % 2 != 0) {
            throw new IllegalArgumentException("Invalid hex string: " + hex);
        }
        byte[] bytes = new byte[hex.length() / 2];
        for (int i = 0; i < bytes.length; i++) {
            // Parse each pair of hex characters as an integer, then cast to byte
            bytes[i] = (byte) Integer.parseInt(hex.substring(i * 2, i * 2 + 2), 16);
        }
        return bytes;
    }


    // ----------------------------------------------------------------
    // HELPERS (package-accessible for ServerUserManager)
    // ----------------------------------------------------------------

    /**
     * Public constant-time string comparison.
     * Used by ServerUserManager to compare pre-hashed password strings
     * without exposing the internal implementation details.
     *
     * @param a  first string
     * @param b  second string
     * @return   true if both strings are identical
     */
    public static boolean constantTimeEqualsPublic(String a, String b) {
        return constantTimeEquals(a, b);
    }

    // ----------------------------------------------------------------
    // PRIVATE HELPERS
    // ----------------------------------------------------------------

    /**
     * Constant-time string comparison.
     * Iterates through ALL characters regardless of where a mismatch
     * occurs, preventing timing side-channel attacks.
     */
    private static boolean constantTimeEquals(String a, String b) {
        if (a == null || b == null) return false;
        if (a.length() != b.length()) return false;

        int result = 0;
        for (int i = 0; i < a.length(); i++) {
            // XOR: if characters are equal, XOR produces 0; otherwise non-zero
            result |= a.charAt(i) ^ b.charAt(i);
        }
        // result == 0 only if every character matched
        return result == 0;
    }

    // Private constructor — utility class, never instantiated
    private PasswordUtil() {}
}
